# Generated by Django 2.2 on 2019-04-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20190427_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryList',
            new_name='Item',
        ),
    ]
